//tealium universal tag - utag.9 ut4.0.201705030213, Copyright 2017 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState==='complete'||this.readyState==='loaded')&&!b.hFlag){b.hFlag=1;o.cb();}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb();}};}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.map={"_dcSource":"src","_dcCategory":"cat","_dcType":"type","_dcu":"u","_dcu1":"u1","_dcu4":"u4","_dcu5":"u5","_dcu9":"u9","_dcu10":"u10","_dcu11":"u11","_dcu18":"u18","_dcCost":"cost","_dcOrder":"order_id"};u.extend=[function(a,b){try{if(typeof b['_dcValues']!='undefined'){try{b['_dcSource']=b['_dcValues'].split('|')[0]}catch(e){};try{b['_dcType']=b['_dcValues'].split('|')[1]}catch(e){};try{b['_dcCategory']=b['_dcValues'].split('|')[2]}catch(e){}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page.condition'].toString().toLowerCase()=='pp_pcp'.toLowerCase()){b['_dcu1']=b['purchase.orderType'];b['_dcu9']=b['page.platform'];b['_dcu10']=b['page.language'];try{b['_dcu11']=b['purchase.orderType']=='NPP'||b['purchase.orderType']=='NSP'?'Prepaid':'Postpaid'}catch(e){};b['_dcu18']=b['purchase.productId'];b['_dcCost']=b['purchase.orderTotal'];b['_dcOrder']=b['purchase.orderNumber']}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page.condition'].toString().toLowerCase().indexOf('pcp'.toLowerCase())>-1){b['_dcu1']=b['purchase.orderType'];b['_dcu9']=b['page.platform'];b['_dcu10']=b['page.language'];try{b['_dcu11']=b['purchase.orderType']=='NPP'||b['purchase.orderType']=='NSP'?'Prepaid':'Postpaid'}catch(e){};b['_dcu18']=b['page.productString.productId'];b['_dcCost']=b['purchase.orderTotal'];b['_dcOrder']=b['purchase.orderNumber'];b['_dcu5']=b['purchase.shippingZipCode'];b['_dcu']=b['purchase.orderType'];b['_dcu4']=b['page.productString.productId']}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page.condition'].toString().toLowerCase().indexOf('fios_pcp'.toLowerCase())>-1){b['_dcOrder']=b['purchase.orderNumber'];b['_dcu']=b['purchase.orderType']}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page.condition'].toString().toLowerCase().indexOf('sl_landing'.toLowerCase())>-1){b['_dcu9']=b['page.platform'];b['_dcu10']=b['page.language']}}catch(e){utag.DB(e)}},function(a,b){try{if(b['page.condition'].toString().toLowerCase().indexOf('sl_results'.toLowerCase())>-1){b['_dcu9']=b['page.platform'];b['_dcu10']=b['page.language']}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,g;u.data={"qsp_delim":";","kvp_delim":"=","base_url":"","src":"","type":"","cat":"","multicat":"","ord":"","cost":"","qty":0,"total_qty":0,"countertype":"standard","conversioncount":"single","order_id":"","order_subtotal":"","product_id":[],"product_quantity":[],"product_unit_price":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];g=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(/^(cat|multicat|type|src|cost|qty|countertype|conversioncount|ord|order_id|order_subtotal|product_id|product_quantity|product_unit_price)$/.test(e[f])){u.data[e[f]]=b[d];}else{u.data[e[f]]=b[d];g.push(e[f]+u.data.kvp_delim+encodeURIComponent(b[d]))}}}}
u.data.order_id=u.data.order_id||u.data.ord||b._corder||"";u.data.order_subtotal=u.data.cost||u.data.order_subtotal||b._csubtotal||b._ctotal||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if((u.data.qty&&u.data.qty.length>0)||(u.data.product_quantity.length===0&&b._cquan!==undefined)){u.data.product_quantity=u.data.qty||b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.data.base_url='//'+u.data.src+'.fls.doubleclick.net/activityi;src='+u.data.src+';type='+u.data.type+';';if(u.data.multicat===""){u.data.multicat_arr=[u.data.cat];}else{u.data.multicat_arr=u.data.multicat.split(';');}
if(u.data.order_id){if(u.data.conversioncount==="multi"&&u.data.product_quantity.length>0){for(f=0;f<u.data.product_quantity.length;f++){u.data.total_qty+=parseInt(u.data.product_quantity[f]);}
u.data.qty=u.data.total_qty;}else{u.data.qty=1;}
c.push('qty='+(u.data.qty));c.push('cost='+(u.data.order_subtotal));if(g.length>0){c.push(g.join(';'));}
c.push('ord='+(u.data.order_id));}else if(u.data.countertype==='standard'){if(g.length>0){c.push(g.join(';'));}
c.push('ord='+(Math.random()*10000000000000));}else if(u.data.countertype==='unique'){if(g.length>0){c.push(g.join(';'));}
c.push('ord=1');c.push('num='+(Math.random()*10000000000000));}else{if(g.length>0){c.push(g.join(';'));}
c.push('ord='+(u.data.order_id?u.data.order_id:window.utag.data['cp.utag_main_ses_id']));}
for(f=0;f<u.data.multicat_arr.length;f++){u.loader({"type":"iframe","src":u.data.base_url+'cat='+u.data.multicat_arr[f]+((c.length>0)?';'+c.join(u.data.qsp_delim):'')+'?',"loc":"body","id":'utag_9_iframe'});}}};utag.o[loader].loader.LOAD(id);}('9','vzw.main'));}catch(error){utag.DB(error);}
