//tealium universal tag - utag.545 ut4.0.201708091356, Copyright 2017 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){jQuery('#nav-cart').on('click','>a,>span',function(){setTimeout(function(){if(jQuery('#nav-cart .cart-req').css('display')=='none'){var miniCartInterval=setInterval(function(){var x=jQuery('#nav-tab4').hasClass('active');if(x==true){vzwLinkTrack('Mini Cart Open');jQuery('#minicart-item-list .minicart-item').each(function(){var sku='';var pName=jQuery(this).find('.product-title').html();var qty=jQuery(this).find('.minicart-item-qty').html();var cost=jQuery(this).find('.price').html();s.products='accessories;'+sku+';'+qty+';'+cost;});if(jQuery('span.count').html()==0){s.pageName="/store/accessories/empty mini cart";vzwPageView("/store/accessories/empty mini cart","scView");}else{s.pageName="/store/accessories/mini cart";vzwPageView("/store/accessories/mini cart","scView");}
jQuery("#minicart-box").one('click','#minicart-banner-box .minicart-banner',function(){var offerName=jQuery(this).children("h3").text().replace(/\s{2,}/g,' ');var cta=jQuery(this).children("a").text().trim();if(offerName.indexOf("Shipping")>=0){vzwPageView("/store/accessories/free shipping");vzwLinkTrack('Promo Pod:'+offerName+':'+cta,"/store/accessories/free shipping");}else{vzwLinkTrack('Promo Pod:'+offerName+':'+cta,"/store/accessories/free shipping");}});jQuery("#minicart-box").one('click','#view-cart a',function(){if(jQuery('span.count').html()==0){s.pageName="/store/accessories/empty mini cart"}else{s.pageName="/store/accessories/mini cart";}
vzwLinkTrack('View Cart',s.pageName);});jQuery("#minicart-box").one('click','#checkout input.add-cart-cta',function(){if(jQuery('span.count').html()==0){s.pageName="/store/accessories/empty mini cart"}else{s.pageName="/store/accessories/mini cart";}
vzwLinkTrack('Checkout',s.pageName);});jQuery('#minicart-box').one('click','.empty-mini-signin a',function(){if(jQuery('span.count').html()==0){s.pageName="/store/accessories/empty mini cart"}else{s.pageName="/store/accessories/mini cart";}
vzwLinkTrack('Sign In',s.pageName);});vzwTagging.ajaxListener.create(function(){var x=jQuery('.cart-req').not('[class*="hidden"]');if(x.length==0){return;}
return x;},function(n){if(jQuery('span.count').html()==0){s.pageName="/store/accessories/empty mini cart";}else{s.pageName="/store/accessories/mini cart";}
vzwLinkTrack('Mini Cart Close',s.pageName);});}
clearInterval(miniCartInterval);s.pageName=vzwDL.page.pageName;},500);jQuery("#minicart-box").off('click','#minicart-banner-box .minicart-banner')
jQuery("#minicart-box").off('click','#view-cart a')
jQuery("#minicart-box").off('click','#checkout input.add-cart-cta')
jQuery('#minicart-box').off('click','.empty-mini-signin a')}},500);});}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("545","vzw.main");}catch(error){utag.DB(error);}
