//tealium universal tag - utag.1041 ut4.0.201804302018, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if((b['dom.pathname'].toString().toLowerCase().indexOf('/military'.toLowerCase())>-1&&b['page.flowType'].toString().toLowerCase().indexOf('military'.toLowerCase())>-1)){(function(){var analyticsFormatter=function(str){if(!str){return str;}
return str.replace(/(<br\s*\/?>)|[\u0024\u00ae\u00a9\u2122]/g,' ').replace(/\s\s+/g,' ').trim().toLowerCase();};jQuery('#pageWrapper').on('mousedown touchstart','a, .tabs_tab',function(){var ref=jQuery(this),conditionals={'2':function(ref){return ref.find('h2:first').text();},'3':function(ref){var finalText='';if(ref.attr('data-tab')==='wirelessDiscount'){finalText='wireless tab';}else if(ref.attr('data-tab')==='fiosDiscount'){finalText='fios tab';}else if(ref.parents('[data-tabs-content="wirelessDiscount"]').length>0){finalText='wireless tab:'+ref.closest('.swiper_item').find('h2:first').text()
if(finalText==='wireless tab:Statuscheck.'){finalText=finalText+':clicked';}else{finalText=finalText+':'+(ref.text().trim()||'clicked');}}else if(ref.parents('[data-tabs-content="fiosDiscount"]').length>0){finalText='fios tab:'+ref.closest('div.columns').find('h2:first').text()+':'+ref.text();}
return finalText;},'4':function(ref){return ref.closest('.columns').find('h2:first').text()+':'+(ref.text().trim()||'click');}},tier=ref.parents('.section').index()+1,lName=conditionals[tier]?conditionals[tier](ref).toLowerCase():ref.text().toLowerCase(),fs='L'+tier+':'+lName;if(lName){vzwLinkTrack(analyticsFormatter(fs));}});})();}}catch(e){utag.DB(e)}},function(a,b){try{if(b['dom.pathname'].toString().toLowerCase().indexOf('/mothers-day'.toLowerCase())>-1){(function(){var sectionsList=jQuery('section');var getSectionHeader=function(ref){return ref.closest('section').find('h2:first').html();}
var slideItems=function(ref){if(ref.text().toLowerCase()!=='see details'){return ref.closest('.slick-item').find('a:first').html();}
return'';};var analyticsFormatter=function(str){if(!str){return str;}
return str.replace(/(<br\s*\/?>)|[\u0024\u00ae\u00a9\u2122]/g,' ').replace(/\s\s+/g,' ').trim().toLowerCase();};jQuery('body').on('click','a, button, .button',function(){var ref=jQuery(this),conditionals={'3':slideItems,'5':slideItems,'6':slideItems,'8':slideItems},tier=sectionsList.index(ref.closest('section'))+1,lName=analyticsFormatter(conditionals[tier]?conditionals[tier](ref):ref.text()),fs='L'+tier+':'+analyticsFormatter(getSectionHeader(ref))+':'+lName;if(lName){vzwLinkTrack(fs);}});})();}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("1041","vzw.main");}catch(error){utag.DB(error);}
