//tealium universal tag - utag.519 ut4.0.201803192352, Copyright 2018 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){jQuery('#searchMap area').on('click',function(){var lName=jQuery(this).attr('alt');vzwLinkTrack(lName);});jQuery('.iCheck-helper').eq(1).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected';}
vzwLinkTrack('Store type:Filter:'+lName+selDes);});jQuery('.iCheck-helper').eq(2).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected';}
vzwLinkTrack('Store type:Filter:'+lName+selDes);});jQuery('.iCheck-helper').eq(3).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected';}
vzwLinkTrack('Store Features:Filter:'+lName+selDes);});jQuery('.iCheck-helper').eq(4).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected';}
vzwLinkTrack('Store Features:Filter:'+lName+selDes);});jQuery('.iCheck-helper').eq(5).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected ';}
vzwLinkTrack('Store Features:Filter:'+lName+selDes);});jQuery('.iCheck-helper').eq(6).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected ';}
vzwLinkTrack('Appointment Services:Filter:'+lName+selDes);});jQuery('.iCheck-helper').eq(7).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected ';}
vzwLinkTrack('Appointment Services:Filter:'+lName+selDes);});jQuery('.iCheck-helper').eq(8).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected ';}
vzwLinkTrack('Appointment Services:Filter:'+lName+selDes);});jQuery('.wrapper .store-filter').on('mousedown','a.btn.small',function(){var lName=jQuery(this).data('tracking');lName='Filter:'+lName;vzwLinkTrack(lName);setTimeout(function(){if(jQuery('.modal-content:visible').length>0){vzwPageView("/desktop/my verizon/postpay/no stores found overlay");jQuery('button').on('mousedown',function(){var lName=jQuery(this).text().toLowerCase().replace(/^\s\s*/,'').replace(/\s\s*$/,'');vzwLinkTrack('Close Overlay',"/desktop/my verizon/postpay/no stores found overlay");});}},2000);});jQuery('.wrapper').on('click','.products .information .show-direction',function(){var storeName=jQuery(this).parent().siblings('h2').text();var lName=jQuery(this).text().replace(/^\s\s*/,'').replace(/\s\s*$/,'');vzwLinkTrack(lName);});jQuery('.wrapper').on('click','.products .information .storePageLink',function(){var storeName=jQuery(this).parent().siblings('h2').text();var lName=jQuery(this).text().replace(/^\s\s*/,'').replace(/\s\s*$/,'');lName=lName+':'+storeName;vzwLinkTrack(lName);});jQuery('.wrapper').on('click','.list-view-pager .pager-item a',function(){var lName=jQuery(this).text().replace(/^\s\s*/,'').replace(/\s\s*$/,'');vzwLinkTrack(lName);});jQuery('.container-wrapper').on('mousedown','#SLSmallPromo a',function(){var lName=jQuery(this).text().replace(/^\s\s*/,'').replace(/\s\s*$/,'');lName='Banner:Free ISPU:'+lName;vzwLinkTrack(lName);});jQuery('#storeLocator').on('click','.banner-content a',function(){var catName=jQuery(this).parents('.banner-content').find('h2').text().replace(/^\s\s*/,'').replace(/\s\s*$/,'').toLowerCase();var lName=jQuery(this).text().replace(/^\s\s*/,'').replace(/\s\s*$/,'').toLowerCase();vzwLinkTrack(catName+':'+lName);});jQuery('.iCheck-helper').eq(7).on('mousedown',function(){var lName=jQuery(this).parent().parent().text().trim().replace(/\W+/g," ");if(jQuery(this).parent().hasClass('checked')){selDes=':Deselected';}else{selDes=':Selected ';}
vzwLinkTrack(lName+selDes);});}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("519","vzw.main");}catch(error){utag.DB(error);}
